Movie.destroy_all

Movie.create(title:"Sonic the Hedgehog 3", overview:"Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.", poster_path:"https://www.google.com/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg", release_date:"2024-12-19", vote_average:7.594, vote_count:621, adult:false, backdrop_path:"/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg", original_language:"en", original_title:"Sonic the Hedgehog 3", popularity:2525.912, video:false)
Movie.create(title:"Mufasa: The Lion King", overview:"Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.", poster_path:"https://www.google.com/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg", release_date:"2024-12-18", vote_average:7.4, vote_count:704, adult:false, backdrop_path:"/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg", original_language:"en", original_title:"Mufasa: The Lion King", popularity:2393.715, video:false)
Movie.create(title:"Gladiator II", overview:"Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.", poster_path:"https://www.google.com/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg", release_date:"2024-11-05", vote_average:6.751, vote_count:2359, adult:false, backdrop_path:"/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg", original_language:"en", original_title:"Gladiator II", popularity:1720.821, video:false)
Movie.create(title:"Venom: The Last Dance", overview:"Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.", poster_path:"https://www.google.com/aosm8NMQ3UyoBVpSxyimorCQykC.jpg", release_date:"2024-10-22", vote_average:6.812, vote_count:2392, adult:false, backdrop_path:"/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg", original_language:"en", original_title:"Venom: The Last Dance", popularity:1694.909, video:false)
Movie.create(title:"Kraven the Hunter", overview:"Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.", poster_path:"https://www.google.com/i47IUSsN126K11JUzqQIOi1Mg1M.jpg", release_date:"2024-12-11", vote_average:6.267, vote_count:465, adult:false, backdrop_path:"/iFsWkmAcu1QcMJ2LhqN8bU0Oj7.jpg", original_language:"en", original_title:"Kraven the Hunter", popularity:1682.267, video:false)
Movie.create(title:"Moana 2", overview:"After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.", poster_path:"https://www.google.com/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg", release_date:"2024-11-21", vote_average:7, vote_count:855, adult:false, backdrop_path:"/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg", original_language:"en", original_title:"Moana 2", popularity:1432.939, video:false)
Movie.create(title:"Nr. 24", overview:"On the brink of the Second World War, a young Norwegian man's drive to resist the Nazis sets a new course for his future – and the future of his country.", poster_path:"https://www.google.com/rzsmKSFEsEWBLbJ968abffnfYZ7.jpg", release_date:"2024-10-30", vote_average:7.4, vote_count:123, adult:false, backdrop_path:"/3WnoZw50qIfXsFnKr0LddEh5Jnf.jpg", original_language:"no", original_title:"Nr. 24", popularity:1373.294, video:false)
Movie.create(title:"Wicked", overview:"In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.", poster_path:"https://www.google.com/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg", release_date:"2024-11-20", vote_average:7.114, vote_count:1308, adult:false, backdrop_path:"/fzjH7kt1017R9EckLDmWmH5pGhD.jpg", original_language:"en", original_title:"Wicked", popularity:1270.61, video:false)
Movie.create(title:"Werewolves", overview:"A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.", poster_path:"https://www.google.com/cRTctVlwvMdXVsaYbX5qfkittDP.jpg", release_date:"2024-12-04", vote_average:6.536, vote_count:193, adult:false, backdrop_path:"/rhc8Mtuo3Kh8CndnlmTNMF8o9pU.jpg", original_language:"en", original_title:"Werewolves", popularity:1096.46, video:false)
Movie.create(title:"The Lord of the Rings: The War of the Rohirrim", overview:"A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.", poster_path:"https://www.google.com/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg", release_date:"2024-12-05", vote_average:6.5, vote_count:323, adult:false, backdrop_path:"/k24eZq5I3jyz4htPkZCRpnUmBzE.jpg", original_language:"en", original_title:"The Lord of the Rings: The War of the Rohirrim", popularity:1049.714, video:false)
Movie.create(title:"Culpa tuya", overview:"The love between Noah and Nick seems unwavering despite their parents' attempts to separate them. But his job and her entry into college open up their lives to new relationships that will shake the foundations of both their relationship and the Leister family itself.", poster_path:"https://www.google.com/1sQA7lfcF9yUyoLYC0e6Zo3jmxE.jpg", release_date:"2024-12-26", vote_average:7.154, vote_count:870, adult:false, backdrop_path:"/bx6LoGl8L3hwgOCoD2H8JgIu7uC.jpg", original_language:"es", original_title:"Culpa tuya", popularity:1035.271, video:false)
Movie.create(title:"Red One", overview:"After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.", poster_path:"https://www.google.com/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg", release_date:"2024-10-31", vote_average:7.1, vote_count:2044, adult:false, backdrop_path:"/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg", original_language:"en", original_title:"Red One", popularity:972.76, video:false)
Movie.create(title:"Solo Leveling -ReAwakening-", overview:"Over a decade after 'gates' connecting worlds appeared, awakening 'hunters' with superpowers, weakest hunter Sung Jinwoo encounters a double dungeon and accepts a mysterious quest, becoming the only one able to level up, changing his fate. A catch-up recap of the first season coupled with an exclusive sneak peek of the first two episodes of the highly anticipated second season in one momentous theatrical fan experience.", poster_path:"https://www.google.com/uzHMp5heVLR68kbbUEXFPsmxYsM.jpg", release_date:"2024-11-26", vote_average:7, vote_count:76, adult:false, backdrop_path:"/au3o84ub27qTZiMiEc9UYzN74V3.jpg", original_language:"ja", original_title:"Solo Leveling -ReAwakening-", popularity:814.947, video:false)

