Movie.create([
  {
    adult: false,
    backdrop_path: "/b85bJfrTOSJ7M5Ox0yp4lxIxdG1.jpg",
    genre_ids: [28, 878, 35, 10751],
    movie_id: 939243,
    original_language: "en",
    original_title: "Sonic the Hedgehog 3",
    overview: "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
    popularity: 6277.745,
    poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
    release_date: "2024-12-19",
    title: "Sonic the Hedgehog 3",
    video: false,
    vote_average: 7.806,
    vote_count: 906
  },
  {
    adult: false,
    backdrop_path: "/v9Du2HC3hlknAvGlWhquRbeifwW.jpg",
    genre_ids: [28, 878, 12, 14, 53],
    movie_id: 539972,
    original_language: "en",
    original_title: "Kraven the Hunter",
    overview: "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
    popularity: 3611.48,
    poster_path: "/i47IUSsN126K11JUzqQIOi1Mg1M.jpg",
    release_date: "2024-12-11",
    title: "Kraven the Hunter",
    video: false,
    vote_average: 6.585,
    vote_count: 767
  },
  {
    adult: false,
    backdrop_path: "/xZm5YUNY3PlYD1Q4k7X8zd2V4AK.jpg",
    genre_ids: [28, 35],
    movie_id: 993710,
    original_language: "en",
    original_title: "Back in Action",
    overview: "Fifteen years after vanishing from the CIA to start a family, elite spies Matt and Emily jump back into the world of espionage when their cover is blown.",
    popularity: 2277.176,
    poster_path: "/3L3l6LsiLGHkTG4RFB2aBA6BttB.jpg",
    release_date: "2025-01-15",
    title: "Back in Action",
    video: false,
    vote_average: 6.727,
    vote_count: 442
  },
  {
    adult: false,
    backdrop_path: "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
    genre_ids: [12, 10751, 16],
    movie_id: 762509,
    original_language: "en",
    original_title: "Mufasa: The Lion King",
    overview: "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
    popularity: 1971.014,
    poster_path: "/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg",
    release_date: "2024-12-18",
    title: "Mufasa: The Lion King",
    video: false,
    vote_average: 7.441,
    vote_count: 843
  },
  {
    adult: false,
    backdrop_path: "/hAQnXxOwCjgYcKRgTdYPRC8neqL.jpg",
    genre_ids: [28, 18],
    movie_id: 811941,
    original_language: "te",
    original_title: "దేవర: Part 1",
    overview: "Devara, a fearless man from a coastal region, embarks on a perilous journey into the treacherous world of the sea to safeguard the lives of his people. Unbeknownst to him, his brother Bhaira is plotting a conspiracy against him. As events unfold, Devara passes on his legacy to his mild-mannered and timid son, Varada.",
    popularity: 1469.737,
    poster_path: "/A9ENz6d4lC3UYOX8Z1gJwDEo1sM.jpg",
    release_date: "2024-09-26",
    title: "Devara: Part 1",
    video: false,
    vote_average: 7.1,
    vote_count: 40
  },
  {
    adult: false,
    backdrop_path: "/fYnEbgoNCxW9kL0IgOgtJb9JTBU.jpg",
    genre_ids: [27],
    movie_id: 426063,
    original_language: "en",
    original_title: "Nosferatu",
    overview: "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
    popularity: 1359.239,
    poster_path: "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
    release_date: "2024-12-25",
    title: "Nosferatu",
    video: false,
    vote_average: 6.66,
    vote_count: 1348
  },
  {
    adult: false,
    backdrop_path: "/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg",
    genre_ids: [16, 12, 10751, 35, 9648],
    movie_id: 1241982,
    original_language: "en",
    original_title: "Moana 2",
    overview: "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
    popularity: 1330.002,
    poster_path: "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
    release_date: "2024-11-21",
    title: "Moana 2",
    video: false,
    vote_average: 7.002,
    vote_count: 892
  },
  {
    adult: false,
    backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
    genre_ids: [28, 878, 12],
    movie_id: 912649,
    original_language: "en",
    original_title: "Venom: The Last Dance",
    overview: "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    popularity: 1275.023,
    poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
    release_date: "2024-10-22",
    title: "Venom: The Last Dance",
    video: false,
    vote_average: 6.8,
    vote_count: 2520
  },
  {
    adult: false,
    backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    genre_ids: [28, 12, 18],
    movie_id: 558449,
    original_language: "en",
    original_title: "Gladiator II",
    overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
    popularity: 1224.01,
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    release_date: "2024-11-05",
    title: "Gladiator II",
    video: false,
    vote_average: 6.762,
    vote_count: 2478
  },
  {
    adult: false,
    backdrop_path: "/pqulyfkug9A7TmmRn5zrbRA8TAY.jpg",
    genre_ids: [28, 35],
    movie_id: 1255788,
    original_language: "fr",
    original_title: "Le Jardinier",
    overview: "Every year the Prime Minister has a list of all kinds of troublemakers eliminated in the name of the famous Reason of State. Serge Shuster, Special Adviser to the President of the Republic, finds himself on this list, better known as the Matignon List. Condemned to certain death and at the heart of an implacable plot and a state secret that also put his family in danger, Serge, his wife and children have only one hope left - their gardener, Léo, who hates it when « slugs » invade his garden... Especially those that want to kill innocent families.",
    popularity: 1119.139,
    poster_path: "/5T9WR7vIOnHm6xhVt5zBuPbBgt1.jpg",
    release_date: "2025-01-10",
    title: "The Gardener",
    video: false,
    vote_average: 4.9,
    vote_count: 92
  },
  {
    adult: false,
    backdrop_path: "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
    genre_ids: [18, 10749, 14],
    movie_id: 402431,
    original_language: "en",
    original_title: "Wicked",
    overview: "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
    popularity: 1055.946,
    poster_path: "/2E1x1qcHqGZcYuYi4PzVZjzg8IV.jpg",
    release_date: "2024-11-20",
    title: "Wicked",
    video: false,
    vote_average: 6.951,
    vote_count: 1447
  },
  {
    adult: false,
    backdrop_path: "/uOQgMhYyu7dkXdHoRkCqZIF32M6.jpg",
    genre_ids: [28, 12],
    movie_id: 1241320,
    original_language: "ja",
    original_title: "キングダム　大将軍の帰還",
    overview: "Depicts a continuation of the \"Battle of Mayang\", an all-out war against the neighboring country Zhao that Shin and Wang Ki fought in in the previous work \"Flame of Fate\".",
    popularity: 1010.464,
    poster_path: "/qZKKwXyZ92K0mIRpf2FbCkQa7oO.jpg",
    release_date: "2024-07-12",
    title: "Kingdom IV: Return of the Great General",
    video: false,
    vote_average: 7.1,
    vote_count: 57
  },
  {
    adult: false,
    backdrop_path: "/5o4iH2N4jX3HmNCBbC6rJqxtWj2.jpg",
    genre_ids: [27, 53],
    movie_id: 1222064,
    original_language: "en",
    original_title: "River of Blood",
    overview: "Four kayakers take the wrong river into a jungle inhabited by a tribe of merciless cannibals.",
    popularity: 855.909,
    poster_path: "/7lkm4eAvHy1uCs48GEwMxgwNdgd.jpg",
    release_date: "2024-08-29",
    title: "River of Blood",
    video: false,
    vote_average: 6.8,
    vote_count: 12
  },
  {
    adult: false,
    backdrop_path: "/k24eZq5I3jyz4htPkZCRpnUmBzE.jpg",
    genre_ids: [10749, 18],
    movie_id: 1156593,
    original_language: "es",
    original_title: "Culpa tuya",
    overview: "The love between Noah and Nick seems unwavering despite their parents' attempts to separate them. But his job and her entry into college open up their lives to new relationships that will shake the foundations of both their relationship and the Leister family itself.",
    popularity: 855,
    poster_path: "/1sQA7lfcF9yUyoLYC0e6Zo3jmxE.jpg",
    release_date: "2024-12-26",
    title: "Your Fault",
    video: false,
    vote_average: 7.17,
    vote_count: 926
  },
  {
    adult: false,
    backdrop_path: "/bFPqSvR2EmWQ9AlzWkC801XpoAZ.jpg",
    genre_ids: [27, 878],
    movie_id: 933260,
    original_language: "en",
    original_title: "The Substance",
    overview: "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
    popularity: 850.494,
    poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
    release_date: "2024-09-07",
    title: "The Substance",
    video: false,
    vote_average: 7.13,
    vote_count: 3382
  },
  {
    adult: false,
    backdrop_path: "/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg",
    genre_ids: [16, 14, 28, 12],
    movie_id: 839033,
    original_language: "en",
    original_title: "The Lord of the Rings: The War of the Rohirrim",
    overview: "A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.",
    popularity: 841.588,
    poster_path: "/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg",
    release_date: "2024-12-05",
    title: "The Lord of the Rings: The War of the Rohirrim",
    video: false,
    vote_average: 6.6,
    vote_count: 355
  },
  {
    adult: false,
    backdrop_path: "/i3e7uwZOXks3PMvTOf4yQXbNxkI.jpg",
    genre_ids: [28, 53],
    movie_id: 1081012,
    original_language: "en",
    original_title: "Aftermath",
    overview: "A returning war veteran, stricken with PTSD, gets trapped with his teenage sister on Boston's Tobin Memorial Bridge when a heavily armed group of ex-military revolutionaries take everyone hostage.",
    popularity: 830.238,
    poster_path: "/gEHIVyJB9VWLF3cuJOpYjJjegd1.jpg",
    release_date: "2024-09-27",
    title: "Aftermath",
    video: false,
    vote_average: 6.3,
    vote_count: 58
  },
  {
    adult: false,
    backdrop_path: "/fzjH7kt1017R9EckLDmWmH5pGhD.jpg",
    genre_ids: [28, 27, 53],
    movie_id: 970450,
    original_language: "en",
    original_title: "Werewolves",
    overview: "A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.",
    popularity: 820.569,
    poster_path: "/cRTctVlwvMdXVsaYbX5qfkittDP.jpg",
    release_date: "2024-12-04",
    title: "Werewolves",
    video: false,
    vote_average: 6.4,
    vote_count: 222
  },
  {
    adult: false,
    backdrop_path: "/cjEcqdRdPQJhYre3HUAc5538Gk8.jpg",
    genre_ids: [28, 14, 35],
    movie_id: 845781,
    original_language: "en",
    original_title: "Red One",
    overview: "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.",
    popularity: 790.714,
    poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
    release_date: "2024-10-31",
    title: "Red One",
    video: false,
    vote_average: 7.119,
    vote_count: 2143
  },
  {
    adult: false,
    backdrop_path: "/3WnoZw50qIfXsFnKr0LddEh5Jnf.jpg",
    genre_ids: [10752, 36, 18],
    movie_id: 1222248,
    original_language: "no",
    original_title: "Nr. 24",
    overview: "On the brink of the Second World War, a young Norwegian man's drive to resist the Nazis sets a new course for his future – and the future of his country.",
    popularity: 731.73,
    poster_path: "/rzsmKSFEsEWBLbJ968abffnfYZ7.jpg",
    release_date: "2024-10-30",
    title: "Number 24",
    video: false,
    vote_average: 7.256,
    vote_count: 162
  },
  {
    adult: false,
    backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genre_ids: [18, 80],
    movie_id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview: "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 175.407,
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 27572
  },
  {
    adult: false,
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    movie_id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 201.059,
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.689,
    vote_count: 20919
  },
  {
    adult: false,
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    movie_id: 240,
    original_language: "en",
    original_title: "The Godfather Part II",
    overview: "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 102.946,
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    video: false,
    vote_average: 8.6,
    vote_count: 12620
  },
  {
    adult: false,
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    movie_id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview: "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 136.953,
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    video: false,
    vote_average: 8.567,
    vote_count: 16063
  },
  {
    adult: false,
    backdrop_path: "/bxgTSUenZDHNFerQ1whRKplrMKF.jpg",
    genre_ids: [18],
    movie_id: 389,
    original_language: "en",
    original_title: "12 Angry Men",
    overview: "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    popularity: 74.742,
    poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    video: false,
    vote_average: 8.5,
    vote_count: 8812
  },
  {
    adult: false,
    backdrop_path: "/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg",
    genre_ids: [16, 10751, 14],
    movie_id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview: "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 105.356,
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.5,
    vote_count: 16747
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    movie_id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview: "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 40.698,
    poster_path: "/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.523,
    vote_count: 4453
  },
  {
    adult: false,
    backdrop_path: "/plDp52MirFHc2PMJRMNWoG0kfr3.jpg",
    genre_ids: [18, 28, 80, 53],
    movie_id: 155,
    original_language: "en",
    original_title: "The Dark Knight",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    popularity: 157.488,
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-16",
    title: "The Dark Knight",
    video: false,
    vote_average: 8.518,
    vote_count: 33272
  },
  {
  adult: false,
  backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
  genre_ids: [14, 18, 80],
  movie_id: 497,
  original_language: "en",
  original_title: "The Green Mile",
  overview: "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  popularity: 116.642,
  poster_path: "/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg",
  release_date: "1999-12-10",
  title: "The Green Mile",
  video: false,
  vote_average: 8.5,
  vote_count: 17700
},
{
  adult: false,
  backdrop_path: "/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg",
  genre_ids: [35, 53, 18],
  movie_id: 496243,
  original_language: "ko",
  original_title: "기생충",
  overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  popularity: 131.346,
  poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
  release_date: "2019-05-30",
  title: "Parasite",
  video: false,
  vote_average: 8.5,
  vote_count: 18540
},
{
  adult: false,
  backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
  genre_ids: [53, 80],
  movie_id: 680,
  original_language: "en",
  original_title: "Pulp Fiction",
  overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  popularity: 140.109,
  poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
  release_date: "1994-09-10",
  title: "Pulp Fiction",
  video: false,
  vote_average: 8.488,
  vote_count: 28199
},
{
  adult: false,
  backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
  genre_ids: [16, 10749, 18],
  movie_id: 372058,
  original_language: "ja",
  original_title: "君の名は。",
  overview: "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
  popularity: 74.089,
  poster_path: "/vfJFJPepRKapMd5G2ro7klIRysq.jpg",
  release_date: "2016-08-26",
  title: "Your Name.",
  video: false,
  vote_average: 8.5,
  vote_count: 11530
},
{
  adult: false,
  backdrop_path: "/5JrZAtyk3LwiiAWLW0kwz41XZJC.jpg",
  genre_ids: [12, 14, 28],
  movie_id: 122,
  original_language: "en",
  original_title: "The Lord of the Rings: The Return of the King",
  overview: "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
  popularity: 188.279,
  poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
  release_date: "2003-12-17",
  title: "The Lord of the Rings: The Return of the King",
  video: false,
  vote_average: 8.5,
  vote_count: 24531
},
{
  adult: false,
  backdrop_path: "/mzfx54nfDPTUXZOG48u4LaEheDy.jpg",
  genre_ids: [35, 18, 10749],
  movie_id: 13,
  original_language: "en",
  original_title: "Forrest Gump",
  overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
  popularity: 130.122,
  poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
  release_date: "1994-06-23",
  title: "Forrest Gump",
  video: false,
  vote_average: 8.47,
  vote_count: 27739
},
{
  adult: false,
  backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
  genre_ids: [37],
  movie_id: 429,
  original_language: "it",
  original_title: "Il buono, il brutto, il cattivo",
  overview: "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
  popularity: 89.824,
  poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
  release_date: "1966-12-22",
  title: "The Good, the Bad and the Ugly",
  video: false,
  vote_average: 8.463,
  vote_count: 8748
},
{
  adult: false,
  backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
  genre_ids: [28, 18],
  movie_id: 346,
  original_language: "ja",
  original_title: "七人の侍",
  overview: "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
  popularity: 46.574,
  poster_path: "/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg",
  release_date: "1954-04-26",
  title: "Seven Samurai",
  video: false,
  vote_average: 8.5,
  vote_count: 3761
},
{
  adult: false,
  backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
  genre_ids: [18, 80],
  movie_id: 769,
  original_language: "en",
  original_title: "GoodFellas",
  overview: "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
  popularity: 74.984,
  poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
  release_date: "1990-09-12",
  title: "GoodFellas",
  video: false,
  vote_average: 8.5,
  vote_count: 13042
},
{
  adult: false,
  backdrop_path: "/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg",
  genre_ids: [16, 18, 10752],
  movie_id: 12477,
  original_language: "ja",
  original_title: "火垂るの墓",
  overview: "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
  popularity: 0.071,
  poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
  release_date: "1988-04-16",
  title: "Grave of the Fireflies",
  video: false,
  vote_average: 8.452,
  vote_count: 5659
},
{
  adult: false,
  backdrop_path: "/zoVeIgKzGJzpdG6Gwnr7iOYfIMU.jpg",
  genre_ids: [18, 10749],
  movie_id: 11216,
  original_language: "it",
  original_title: "Nuovo Cinema Paradiso",
  overview: "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
  popularity: 32.159,
  poster_path: "/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",
  release_date: "1988-11-17",
  title: "Cinema Paradiso",
  video: false,
  vote_average: 8.4,
  vote_count: 4424
},
{
  adult: false,
  backdrop_path: "/9REO1DLpmwhrBJY3mYW5eVxkXFM.jpg",
  genre_ids: [12, 18, 878],
  movie_id: 157336,
  original_language: "en",
  original_title: "Interstellar",
  overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
  popularity: 325.977,
  poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
  release_date: "2014-11-05",
  title: "Interstellar",
  video: false,
  vote_average: 8.4,
  vote_count: 36234
},
{
    adult: false,
    backdrop_path: "/i3CAo9UMGsvlU9k3Svd63rRDeZx.jpg",
    genre_ids: [16, 18, 35],
    movie_id: 1064486,
    original_language: "en",
    original_title: "Memoir of a Snail",
    overview: "Forcibly separated from her twin brother when they are orphaned, a melancholic misfit learns how to find confidence within herself amid the clutter of misfortunes and everyday life.",
    popularity: 704.564,
    poster_path: "/lWh5OlerPR1c1cfn1ZLq0lpqFds.jpg",
    release_date: "2024-10-17",
    title: "Memoir of a Snail",
    video: false,
    vote_average: 7.8,
    vote_count: 96
  },
  {
    adult: false,
    backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
    genre_ids: [28, 878, 53],
    movie_id: 1035048,
    original_language: "en",
    original_title: "Elevation",
    overview: "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
    popularity: 686.82,
    poster_path: "/tnfc0NJ3BzhJrGJhkkEd6MHBdq5.jpg",
    release_date: "2024-11-07",
    title: "Elevation",
    video: false,
    vote_average: 6.3,
    vote_count: 365
  },
  {
    adult: false,
    backdrop_path: "/dhz2z8KpD5qd787CkEwPLo6rWpf.jpg",
    genre_ids: [28, 80, 53],
    movie_id: 1249289,
    original_language: "en",
    original_title: "Alarum",
    overview: "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
    popularity: 632.197,
    poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
    release_date: "2025-01-16",
    title: "Alarum",
    video: false,
    vote_average: 6.1,
    vote_count: 41
  },
  {
    adult: false,
    backdrop_path: "/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg",
    genre_ids: [16, 28, 878, 10751],
    movie_id: 1184918,
    original_language: "en",
    original_title: "The Wild Robot",
    overview: "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    popularity: 616.393,
    poster_path: "/vcZfDONCxoOU7mosZEnkhYujBEG.jpg",
    release_date: "2024-09-12",
    title: "The Wild Robot",
    video: false,
    vote_average: 8.364,
    vote_count: 4074
  },
  {
    adult: false,
    backdrop_path: "/kylozAI9Rf1pp7pZ8nFPK4s1s5n.jpg",
    genre_ids: [28, 12, 14, 16],
    movie_id: 1357633,
    original_language: "ja",
    original_title: "俺だけレベルアップな件 -ReAwakening-",
    overview: "Over a decade after 'gates' connecting worlds appeared, awakening 'hunters' with superpowers, weakest hunter Sung Jinwoo encounters a double dungeon and accepts a mysterious quest, becoming the only one able to level up, changing his fate. A catch-up recap of the first season coupled with an exclusive sneak peek of the first two episodes of the highly anticipated second season in one momentous theatrical fan experience.",
    popularity: 596.897,
    poster_path: "/uzHMp5heVLR68kbbUEXFPsmxYsM.jpg",
    release_date: "2024-11-26",
    title: "Solo Leveling -ReAwakening-",
    video: false,
    vote_average: 6.9,
    vote_count: 81
  },
  {
    adult: false,
    backdrop_path: "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
    genre_ids: [16, 14, 12],
    movie_id: 823219,
    original_language: "lv",
    original_title: "Straume",
    overview: "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
    popularity: 555.437,
    poster_path: "/imKSymKBK7o73sajciEmndJoVkR.jpg",
    release_date: "2024-08-29",
    title: "Flow",
    video: false,
    vote_average: 8.408,
    vote_count: 866
  },
  {
    adult: false,
    backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
    genre_ids: [27, 53],
    movie_id: 1138194,
    original_language: "en",
    original_title: "Heretic",
    overview: "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
    popularity: 539.975,
    poster_path: "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
    release_date: "2024-10-31",
    title: "Heretic",
    video: false,
    vote_average: 7.17,
    vote_count: 935
  },
  {
    adult: false,
    backdrop_path: "/dWkdmxIkH9y23s9v1PjQFhTGIwo.jpg",
    genre_ids: [28, 18, 53, 10752],
    movie_id: 1043905,
    original_language: "en",
    original_title: "Dirty Angels",
    overview: "During the United States' 2021 withdrawal from Afghanistan, a group of female soldiers posing as medical relief are sent back in to rescue a group of kidnapped teenagers caught between ISIS and the Taliban.",
    popularity: 532.512,
    poster_path: "/3O3qSGmjRGc10hMwFul8WDxKE5t.jpg",
    release_date: "2024-12-11",
    title: "Dirty Angels",
    video: false,
    vote_average: 6.3,
    vote_count: 160
  },
  {
    adult: false,
    backdrop_path: "/hSuDBuToaEAF4NhHR4haZPw3xN2.jpg",
    genre_ids: [28],
    movie_id: 1075789,
    original_language: "en",
    original_title: "The Ballad of Davy Crockett",
    overview: "In 1815, an American Legend, whose wife has fallen deathly ill, leaving his young children to survive on their own, must fight his way back to them across the many perils found in the Savage Lands of the wild frontier.",
    popularity: 528.619,
    poster_path: "/r3eg88OcnLcCihQdaW3IAOlui4F.jpg",
    release_date: "2024-03-08",
    title: "The Ballad of Davy Crockett",
    video: false,
    vote_average: 3.8,
    vote_count: 5
  },
  {
    adult: false,
    backdrop_path: "/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg",
    genre_ids: [10749, 18],
    movie_id: 1010581,
    original_language: "es",
    original_title: "Culpa mía",
    overview: "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
    popularity: 506.39,
    poster_path: "/w46Vw536HwNnEzOa7J24YH9DPRS.jpg",
    release_date: "2023-06-08",
    title: "My Fault",
    video: false,
    vote_average: 7.9,
    vote_count: 3425
  },
  {
    adult: false,
    backdrop_path: "/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
    genre_ids: [28, 35, 878],
    movie_id: 533535,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    overview: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    popularity: 495.75,
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    release_date: "2024-07-24",
    title: "Deadpool & Wolverine",
    video: false,
    vote_average: 7.6,
    vote_count: 6483
  },
  {
    adult: false,
    backdrop_path: "/4cp40IyTpFfsT2IKpl0YlUkMBIR.jpg",
    genre_ids: [10749, 35, 18],
    movie_id: 1064213,
    original_language: "en",
    original_title: "Anora",
    overview: "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
    popularity: 495.268,
    poster_path: "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
    release_date: "2024-10-14",
    title: "Anora",
    video: false,
    vote_average: 7.004,
    vote_count: 792
  },
  {
    adult: false,
    backdrop_path: "/7bIWKyWdT04HTY3PqLETT8CH7jo.jpg",
    genre_ids: [28, 80, 53],
    movie_id: 974453,
    original_language: "en",
    original_title: "Absolution",
    overview: "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis. Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
    popularity: 477.762,
    poster_path: "/2MeQG5Vq8rUnRAa463BZe5GNhVk.jpg",
    release_date: "2024-10-31",
    title: "Absolution",
    video: false,
    vote_average: 5.844,
    vote_count: 278
  },
  {
    adult: false,
    backdrop_path: "/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg",
    genre_ids: [16, 10751, 35, 878],
    movie_id: 519182,
    original_language: "en",
    original_title: "Despicable Me 4",
    overview: "Gru and Lucy and their girls—Margo, Edith and Agnes—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru also faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
    popularity: 464.163,
    poster_path: "/wWba3TaojhK7NdycRhoQpsG0FaH.jpg",
    release_date: "2024-06-20",
    title: "Despicable Me 4",
    video: false,
    vote_average: 7.071,
    vote_count: 2453
  },
  {
    adult: false,
    backdrop_path: "/bx6LoGl8L3hwgOCoD2H8JgIu7uC.jpg",
    genre_ids: [28, 18],
    movie_id: 1235623,
    original_language: "zh",
    original_title: "目中无人 2",
    overview: "The blind swordsman, skilled in martial arts, named Cheng Xiazi (Xie Miao), accidentally saves Zhang Xiaoyu (Yang Enyou), who has suffered from the destruction of his family. Under the persuasion of the orphan Xiaoyu, Cheng reluctantly keeps him by his side and teaches him skills. Xiaoyu also waits for the opportunity to seek revenge.",
    popularity: 456.613,
    poster_path: "/lxGkinl8TwFdIUffEdTOw95lKL7.jpg",
    release_date: "2024-07-21",
    title: "Eye for an Eye 2",
    video: false,
    vote_average: 7.3,
    vote_count: 14
  },
  {
    adult: false,
    backdrop_path: "/x8Kdi1OJbewkeGuijcSmUWrYyk2.jpg",
    genre_ids: [28, 35, 10751, 878],
    movie_id: 926670,
    original_language: "en",
    original_title: "Henry Danger: The Movie",
    overview: "Henry Hart meets a superfan—eager to fight crime with Kid Danger—who comes into possession of a device that can open up alternate realities. Facing a wild ride, Henry will need his best friend Jasper and his new superfan sidekick to find his way out or be stuck in another dimension forever.",
    popularity: 451.621,
    poster_path: "/dFWj2rOGsqSIX1PHFghbCBgpMnk.jpg",
    release_date: "2025-01-17",
    title: "Henry Danger: The Movie",
    video: false,
    vote_average: 8.7,
    vote_count: 63
  },
  {
    adult: false,
    backdrop_path: "/rhc8Mtuo3Kh8CndnlmTNMF8o9pU.jpg",
    genre_ids: [53, 28],
    movie_id: 1005331,
    original_language: "en",
    original_title: "Carry-On",
    overview: "An airport security officer races to outsmart a mysterious traveler forcing him to let a dangerous item slip onto a Christmas Eve flight.",
    popularity: 449.582,
    poster_path: "/sjMN7DRi4sGiledsmllEw5HJjPy.jpg",
    release_date: "2024-12-05",
    title: "Carry-On",
    video: false,
    vote_average: 6.9,
    vote_count: 1741
  },
  {
    adult: false,
    backdrop_path: "/uFMIiNYUDHzo7YGSg5UUR7VLNma.jpg",
    genre_ids: [35],
    movie_id: 1278099,
    original_language: "es",
    original_title: "El candidato honesto",
    overview: "A former idealistic leader turned corrupt politician is cursed by his grandmother on the eve of the presidential election, forcing him to be honest. Can he win without lies and what will be the conditions?",
    popularity: 447.004,
    poster_path: "/hmV5HPkbQuzgPo11Xm70CMQV3iZ.jpg",
    release_date: "2024-08-08",
    title: "El Candidato Honesto",
    video: false,
    vote_average: 6.879,
    vote_count: 70
  },
  {
    adult: false,
    backdrop_path: "/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
    genre_ids: [16, 12, 35, 10751],
    movie_id: 1022789,
    original_language: "en",
    original_title: "Inside Out 2",
    overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
    popularity: 444.094,
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    release_date: "2024-06-11",
    title: "Inside Out 2",
    video: false,
    vote_average: 7.569,
    vote_count: 5400
  },
  {
    adult: false,
    backdrop_path: "/u8VBaEESHAAc5tDWFc8IjXHw1eC.jpg",
    genre_ids: [35, 18, 10749],
    movie_id: 936621,
    original_language: "ko",
    original_title: "물오징어6969",
    overview: "Three married women had always been dissatisfied sexually with their husbands, and Hyoji, who recently divorced due to her husband's erectile dysfunction. They gathered after a long time and had a drink complaining to each other, and they received a business card from an unidentified handsome man, saying, \"Don't you want to play tteok pounding game?\" The four of them head to the meeting place and meet suspicious agents who were waiting for them.",
    popularity: 433.131,
    poster_path: "/dgSR6qBiQSqaa9QfSMiODAEOF3O.jpg",
    release_date: "2022-01-27",
    title: "Sex Game 6969",
    video: false,
    vote_average: 5.059,
    vote_count: 17
  },
  {
    adult: false,
    backdrop_path: "/qoxriJ6n1qxvG1bBMPnsZBHKGco.jpg",
    genre_ids: [10749, 18, 14],
    movie_id: 11845,
    original_language: "en",
    original_title: "Intimacy",
    overview: "Failed musician Jay abandoned his family and now earns a living as head bartender in a trendy London pub. Every Wednesday afternoon, a woman comes to his house for graphic, almost wordless, sex. One day, Jay follows her and learns about her. This eventually disrupts their relationship.",
    popularity: 239.323,
    poster_path: "/I0mlv1FahaLJqu2ByffMXEn4NN.jpg",
    release_date: "2001-01-20",
    title: "Intimacy",
    video: false,
    vote_average: 6.3,
    vote_count: 509
  },
  {
    adult: false,
    backdrop_path: "/2ERLqcEBaJCIpBVR9O7RAapMGrw.jpg",
    genre_ids: [18, 10749],
    movie_id: 1059128,
    original_language: "en",
    original_title: "Queer",
    overview: "1950. William Lee, an American expat in Mexico City, spends his days almost entirely alone, except for a few contacts with other members of the small American community. His encounter with Eugene Allerton, an expat former soldier, new to the city, shows him, for the first time, that it might be finally possible to establish an intimate connection with somebody.",
    popularity: 239.039,
    poster_path: "/xe4b2TMciLKA1C0JlhWxb4ENLln.jpg",
    release_date: "2024-11-27",
    title: "Queer",
    video: false,
    vote_average: 7.2,
    vote_count: 120
  },
  {
    adult: false,
    backdrop_path: "/eFlx3fW8FHXOktGa7Tzy57RajtG.jpg",
    genre_ids: [18, 10749],
    movie_id: 1357459,
    original_language: "tl",
    original_title: "Tatsulok: Tatlo Magkasalo",
    overview: "Story about a happily married couple visited by an old friend, who ends up stirring the pot by becoming sexually involved with both the husband and the wife.",
    popularity: 237.093,
    poster_path: "/zcmPxGIBxxsGVyYuzNWPCWjlQ8X.jpg",
    release_date: "2024-10-11",
    title: "Tatsulok: Tatlo Magkasalo",
    video: false,
    vote_average: 6.2,
    vote_count: 4
  },
  {
    adult: false,
    backdrop_path: "/w6MAE6cs8F62iAspnIqwVksAENM.jpg",
    genre_ids: [16, 12, 14],
    movie_id: 1208491,
    original_language: "fr",
    original_title: "Zak & Wowo, la légende de Lendarys",
    overview: "At the heart of an imaginary world populated by fantastical creatures and dangerous monsters, the 13 year-old Zak goes in search of his twin brother Kyle, who has disappeared mysteriously. Equipped with a magical jade stone whose superpowers he doesn't yet know how to control, he is joined by his grandmother NaïNaï and Indiana, a beautiful outlaw who can communicate with the world's fantastical creatures. But he is also flanked by Wowo, formerly a 3 meter-tall furry pachyderm, now turned into a tiny, cute and wacky furball by the magical jade stone.",
    popularity: 233.085,
    poster_path: "/tgOq45Aijeup6mqEmOWGzYabaVQ.jpg",
    release_date: "2024-04-25",
    title: "Zak & Wowo: The Legend of Lendarys",
    video: false,
    vote_average: 7,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: "/H39NvEXz23GE9iYQ4qqV4w1zWn.jpg",
    genre_ids: [35, 18],
    movie_id: 728949,
    original_language: "en",
    original_title: "Nightbitch",
    overview: "A woman, thrown into the stay-at-home routine of raising a toddler in the suburbs, slowly embraces the feral power deeply rooted in motherhood, as she becomes increasingly aware of the bizarre and undeniable signs that she may be turning into a dog.",
    popularity: 230.843,
    poster_path: "/h49Pie8gM2jK0UHGFRjfPB3YTd.jpg",
    release_date: "2024-12-06",
    title: "Nightbitch",
    video: false,
    vote_average: 6.2,
    vote_count: 95
  },
  {
    adult: false,
    backdrop_path: "/lLh39Th5plbrQgbQ4zyIULsd0Pp.jpg",
    genre_ids: [28, 12, 878],
    movie_id: 823464,
    original_language: "en",
    original_title: "Godzilla x Kong: The New Empire",
    overview: "Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.",
    popularity: 230.132,
    poster_path: "/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg",
    release_date: "2024-03-27",
    title: "Godzilla x Kong: The New Empire",
    video: false,
    vote_average: 7.1,
    vote_count: 3997
  },
  {
  adult: false,
  backdrop_path: "/u2eA9pqi1q3DvevT7RuDuJHxxBT.jpg",
  genre_ids: [18, 53],
  movie_id: 974950,
  original_language: "fr",
  original_title: "Emilia Pérez",
  overview: "Rita, an underrated lawyer working for a large law firm more interested in getting criminals out of jail than bringing them to justice, is hired by the leader of a criminal organization.",
  popularity: 229.26,
  poster_path: "/7seqaCaaXDNUHOx4DqwpoOH8pPa.jpg",
  release_date: "2024-08-21",
  title: "Emilia Pérez",
  video: false,
  vote_average: 7.7,
  vote_count: 880
},
{
  adult: false,
  backdrop_path: "/llIXQAndg5kB6SWlp6ouUdO7Zxd.jpg",
  genre_ids: [28, 12, 18],
  movie_id: 1084736,
  original_language: "fr",
  original_title: "Le Comte de Monte-Cristo",
  overview: "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
  popularity: 221.408,
  poster_path: "/sAT1P3FGhtJ68anUyJScnMu8t1l.jpg",
  release_date: "2024-06-28",
  title: "The Count of Monte Cristo",
  video: false,
  vote_average: 8.1,
  vote_count: 1293
},
{
  adult: false,
  backdrop_path: "/dGGjuaUR253aAZ2Zhto2Y9TR9l6.jpg",
  genre_ids: [16, 9648, 878, 28],
  movie_id: 1299652,
  original_language: "en",
  original_title: "Watchmen: Chapter II",
  overview: "Suspicious of the events ensnaring their former colleagues, Nite Owl and Silk Spectre are spurred out of retirement to investigate. As they grapple with personal ethics, inner demons and a society turned against them, they race the clock to uncover a deepening plot that might trigger global nuclear war.",
  popularity: 220.73,
  poster_path: "/wUSXPLD3tLWdesY7nYwUitYRI50.jpg",
  release_date: "2024-11-25",
  title: "Watchmen: Chapter II",
  video: false,
  vote_average: 7.4,
  vote_count: 83
},
{
  adult: false,
  backdrop_path: "/nxZDr6UZIhgYJev4yUzWTPZXQ3G.jpg",
  genre_ids: [18, 36],
  movie_id: 1101448,
  original_language: "en",
  original_title: "Unstoppable",
  overview: "Unstoppable is the inspiring true story of Anthony Robles who was born with one leg but whose unbreakable resolve empowered him to defy the odds and pursue his dreams. With the unwavering love and support of his devoted mother and the encouragement of his coaches, Anthony fights through adversity to earn a spot on the Arizona State Wrestling team on his quest to become an NCAA Champion.",
  popularity: 219.314,
  poster_path: "/xanYKxuFkDPrMngvm1NSHVGOEjS.jpg",
  release_date: "2024-12-06",
  title: "Unstoppable",
  video: false,
  vote_average: 3.929,
  vote_count: 78
},
{
  adult: false,
  backdrop_path: "/70AV2Xx5FQYj20labp0EGdbjI6E.jpg",
  genre_ids: [80, 28, 53],
  movie_id: 637649,
  original_language: "en",
  original_title: "Wrath of Man",
  overview: "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
  popularity: 219.239,
  poster_path: "/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
  release_date: "2021-04-22",
  title: "Wrath of Man",
  video: false,
  vote_average: 7.631,
  vote_count: 5413
},
{
  adult: false,
  backdrop_path: "/2k7QEpO7Kvz8mgQPifjWLH6DjtS.jpg",
  genre_ids: [35],
  movie_id: 151586,
  original_language: "it",
  original_title: "La nipote",
  overview: "The summer vacation of a young beautiful girl, at her uncle's country villa.",
  popularity: 218.882,
  poster_path: "/cpGdO3aGbDDxJICQ2vD5bUfb3qO.jpg",
  release_date: "1974-06-14",
  title: "La nipote",
  video: false,
  vote_average: 5.6,
  vote_count: 14
},
{
  adult: false,
  backdrop_path: "/csQSGH0QU8D3Ov5YLEYuHep8ihA.jpg",
  genre_ids: [878, 53, 12, 28],
  movie_id: 1196470,
  original_language: "fr",
  original_title: "Survivre",
  overview: "A couple celebrates their son’s birthday in the middle of the ocean on their boat. A violent storm hits and it brings up hungry creatures from the depths and they fight for their survival.",
  popularity: 218.645,
  poster_path: "/59nsfU5hMG3puDZIGzZzJ1yW8FN.jpg",
  release_date: "2024-06-19",
  title: "Survive",
  video: false,
  vote_average: 5.921,
  vote_count: 114
},
{
    adult: false,
    backdrop_path: "/a3PBAmXUXuazAzr83WNzRaBS33I.jpg",
    genre_ids: [27, 53],
    movie_id: 978796,
    original_language: "en",
    original_title: "Bagman",
    overview: "For centuries and across cultures, parents have warned their children of the legendary Bagman, who snatches innocent children and stuffs them into his vile, rotting bag—never to be seen again. Patrick McKee narrowly escaped such an encounter as a boy, which left him with lasting scars throughout his adulthood. Now, Patrick’s childhood tormentor has returned, threatening the safety of his wife Karina and son Jake.",
    popularity: 217.922,
    poster_path: "/53IK9rlZJbwFYbNnJZiLq7UWxkT.jpg",
    release_date: "2024-09-20",
    title: "Bagman",
    video: false,
    vote_average: 6.3,
    vote_count: 174
  },
  {
    adult: false,
    backdrop_path: "/sAvcdgOzcxFoQPCdEputkyNR7yK.jpg",
    genre_ids: [27],
    movie_id: 1176128,
    original_language: "en",
    original_title: "Santa Isn't Real",
    overview: "After suffering a brutal attack on Christmas Eve, Nikki struggles to convince her friends that the assailant was none other than Ol' Kris Kringle. When Santa returns to terrorize the group in their remote cabin the next Christmas, Nikki and her friends must overcome disbelief as they fight to stay alive.",
    popularity: 209.968,
    poster_path: "/pDRZgeTeefpled1CIRLxdXPgXcv.jpg",
    release_date: "2023-12-08",
    title: "Santa Isn't Real",
    video: false,
    vote_average: 7.2,
    vote_count: 8
  },
  {
    adult: false,
    backdrop_path: "/zD5v1E4joAzFvmAEytt7fM3ivyT.jpg",
    genre_ids: [28, 12, 878],
    movie_id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 207.093,
    poster_path: "/x8AOx0zIfpNKZ1eVW4fhmUiZNqU.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 7.952,
    vote_count: 20393
  },
  {
    adult: false,
    backdrop_path: "/rFKbPDXBzgn4eYBdJXaAPEYIcyA.jpg",
    genre_ids: [35, 10749],
    movie_id: 1397854,
    original_language: "it",
    original_title: "Mica è Colpa Mia",
    overview: "Drowning in debt, two brothers concoct a plan to scam a wealthy heiress and save their home in Naples — but unexpected love soon complicates the scheme.",
    popularity: 205.571,
    poster_path: "/kWBjdB6tP71ed4WTFxuqDZnWVk5.jpg",
    release_date: "2025-01-01",
    title: "The Love Scam",
    video: false,
    vote_average: 6.5,
    vote_count: 81
  },
  {
    adult: false,
    backdrop_path: "/kYgQzzjNis5jJalYtIHgrom0gOx.jpg",
    genre_ids: [16, 10751, 14, 28],
    movie_id: 1011985,
    original_language: "en",
    original_title: "Kung Fu Panda 4",
    overview: "Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.",
    popularity: 204.868,
    poster_path: "/nqXsAaQsKw2gKpkfhIgjXNDRqg7.jpg",
    release_date: "2024-03-02",
    title: "Kung Fu Panda 4",
    video: false,
    vote_average: 7.084,
    vote_count: 2901
  },
  {
    adult: false,
    backdrop_path: "/bfh9Z3Ghz4FOJAfLOAhmc3ccnHU.jpg",
    genre_ids: [12, 14],
    movie_id: 671,
    original_language: "en",
    original_title: "Harry Potter and the Philosopher's Stone",
    overview: "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
    popularity: 204.284,
    poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
    release_date: "2001-11-16",
    title: "Harry Potter and the Philosopher's Stone",
    video: false,
    vote_average: 7.906,
    vote_count: 27773
  },
  {
    adult: false,
    backdrop_path: "/jcEcle0wHoTpEkLmK4AcBKgWI45.jpg",
    genre_ids: [10749, 18],
    movie_id: 1100099,
    original_language: "en",
    original_title: "We Live in Time",
    overview: "An up-and-coming chef and a recent divorcée find their lives forever changed when a chance encounter brings them together, in a decade-spanning, deeply moving romance.",
    popularity: 203.027,
    poster_path: "/oeDNBgnlGF6rnyX1P1K8Vl2f3lW.jpg",
    release_date: "2024-10-10",
    title: "We Live in Time",
    video: false,
    vote_average: 7.51,
    vote_count: 527
  },
  {
  adult: false,
  backdrop_path: "/i9bhxhUBFZHorvK81GNKMJGj2Kt.jpg",
  genre_ids: [99],
  movie_id: 1214667,
  original_language: "en",
  original_title: "Making Squid Game: The Challenge",
  overview: "Go behind the scenes and witness how the \"Squid Game\"-inspired reality show transformed from a scripted drama to a cutthroat, nail-biting competition.",
  popularity: 202.506,
  poster_path: "/78yTLvtsMntVN1cLfzBuZj870pe.jpg",
  release_date: "2023-12-06",
  title: "Making Squid Game: The Challenge",
  video: false,
  vote_average: 6.4,
  vote_count: 41
},
{
  adult: false,
  backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
  genre_ids: [18, 80],
  movie_id: 238,
  original_language: "en",
  original_title: "The Godfather",
  overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
  popularity: 201.059,
  poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
  release_date: "1972-03-14",
  title: "The Godfather",
  video: false,
  vote_average: 8.689,
  vote_count: 20919
},
{
  adult: false,
  backdrop_path: "/en3GU5uGkKaYmSyetHV4csHHiH3.jpg",
  genre_ids: [10752, 28, 18],
  movie_id: 929590,
  original_language: "en",
  original_title: "Civil War",
  overview: "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
  popularity: 200.377,
  poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
  release_date: "2024-04-10",
  title: "Civil War",
  video: false,
  vote_average: 6.875,
  vote_count: 3172
},
{
  adult: false,
  backdrop_path: "/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg",
  genre_ids: [12, 18, 10751, 16],
  movie_id: 420818,
  original_language: "en",
  original_title: "The Lion King",
  overview: "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
  popularity: 196.92,
  poster_path: "/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg",
  release_date: "2019-07-12",
  title: "The Lion King",
  video: false,
  vote_average: 7.112,
  vote_count: 10160
},
{
  adult: false,
  backdrop_path: "/4PAtIaArgPMpKe6fkXw051SYR88.jpg",
  genre_ids: [18],
  movie_id: 50270,
  original_language: "it",
  original_title: "Paprika",
  overview: "Mimma starts working in Madame Colette’s brothel to help her boyfriend financially. There she is rechristened “Paprika,” and falls in love with her first client, naval officer Franco. Despite this attraction, she begins her climb through the sex trade, residing in Italy’s most illustrious brothels.",
  popularity: 196.091,
  poster_path: "/A2VdIkrwBtfbZphrzxpIvEfetjl.jpg",
  release_date: "1991-02-13",
  title: "Paprika",
  video: false,
  vote_average: 7,
  vote_count: 465
},
{
  adult: false,
  backdrop_path: "/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg",
  genre_ids: [12, 28, 878],
  movie_id: 299536,
  original_language: "en",
  original_title: "Avengers: Infinity War",
  overview: "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
  popularity: 195.585,
  poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
  release_date: "2018-04-25",
  title: "Avengers: Infinity War",
  video: false,
  vote_average: 8.24,
  vote_count: 30053
},
{
        adult: false,
        backdrop_path: "/vAAekmyeB9DpRKeJRZNbmIxoNKx.jpg",
        genre_ids: [10749, 18],
        movie_id: 1055110,
        original_language: "ja",
        original_title: "扉を閉めた女教師",
        overview: "A sensual suspense that tells the story of a female teacher and a young student locked in a closed room in the middle of summer.",
        popularity: 193.682,
        poster_path: "/t0R81rsu2chPZEpKiHi8zbOOwR3.jpg",
        release_date: "2021-10-03",
        title: "Female Teacher Closing the Door",
        video: false,
        vote_average: 6,
        vote_count: 3
    },
    {
        adult: false,
        backdrop_path: "/503LUrI9juBk1rktOPzxyMUTDEu.jpg",
        genre_ids: [28, 14, 27],
        movie_id: 957452,
        original_language: "en",
        original_title: "The Crow",
        overview: "Soulmates Eric and Shelly are brutally murdered when the demons of her dark past catch up with them. Given the chance to save his true love by sacrificing himself, Eric sets out to seek merciless revenge on their killers, traversing the worlds of the living and the dead to put the wrong things right.",
        popularity: 193.36,
        poster_path: "/g8TbOXrNMuqq7AaKqdvqS2oG4ob.jpg",
        release_date: "2024-08-21",
        title: "The Crow",
        video: false,
        vote_average: 5.9,
        vote_count: 905
    },
    {
        adult: false,
        backdrop_path: "/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg",
        genre_ids: [28, 12, 878],
        movie_id: 99861,
        original_language: "en",
        original_title: "Avengers: Age of Ultron",
        overview: "When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.",
        popularity: 192.126,
        poster_path: "/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg",
        release_date: "2015-04-22",
        title: "Avengers: Age of Ultron",
        video: false,
        vote_average: 7.273,
        vote_count: 23128
    },
    {
        adult: false,
        backdrop_path: "/xILYyqOGAQcawdNKrJ6ViXOCv15.jpg",
        genre_ids: [18, 10749],
        movie_id: 1412569,
        original_language: "tl",
        original_title: "Hiram na Sandali",
        overview: "An ex-couple accidentally bumps into each other whenever they visit their dog’s grave on its death anniversary. These chance meetings will later lead to a passionate reunion of the two.",
        popularity: 191.98,
        poster_path: "/zNHgQRaflknCSRvKFepqvsHVimG.jpg",
        release_date: "2025-01-16",
        title: "Hiram na Sandali",
        video: false,
        vote_average: 0,
        vote_count: 0
    },
    {
        adult: false,
        backdrop_path: "/2vFuG6bWGyQUzYS9d69E5l85nIz.jpg",
        genre_ids: [878, 12, 28],
        movie_id: 667538,
        original_language: "en",
        original_title: "Transformers: Rise of the Beasts",
        overview: "When a new threat capable of destroying the entire planet emerges, Optimus Prime and the Autobots must team up with a powerful faction known as the Maximals. With the fate of humanity hanging in the balance, humans Noah and Elena will do whatever it takes to help the Transformers as they engage in the ultimate battle to save Earth.",
        popularity: 191.87,
        poster_path: "/gPbM0MK8CP8A174rmUwGsADNYKD.jpg",
        release_date: "2023-06-06",
        title: "Transformers: Rise of the Beasts",
        video: false,
        vote_average: 7.262,
        vote_count: 4753
    },
    {
        adult: false,
        backdrop_path: "/uGmYqxh8flqkudioyFtD7IJSHxK.jpg",
        genre_ids: [18, 80, 53],
        movie_id: 889737,
        original_language: "en",
        original_title: "Joker: Folie à Deux",
        overview: "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
        popularity: 191.348,
        poster_path: "/zPOOyw6HBb5Qo6uaWJ5UxrBR6Ll.jpg",
        release_date: "2024-10-01",
        title: "Joker: Folie à Deux",
        video: false,
        vote_average: 5.52,
        vote_count: 2068
    },
    {
        adult: false,
        backdrop_path: "/5tqkP8NNWdteskVBYPRXE6h82ts.jpg",
        genre_ids: [18],
        movie_id: 592695,
        original_language: "sv",
        original_title: "Pleasure",
        overview: "19 year old Linnéa leaves her small town in Sweden and heads for Los Angeles with the aim of becoming the world's next big porn star, but the road to her goal turns out to be bumpier than she imagined.",
        popularity: 189.836,
        poster_path: "/7Z2K08J0WantJHNa0vLTOmii41l.jpg",
        release_date: "2021-10-08",
        title: "Pleasure",
        video: false,
        vote_average: 6.2,
        vote_count: 580
    },
    {
        adult: false,
        backdrop_path: "/1LSMstNHwJnJD7tpnb8gZcgGNQR.jpg",
        genre_ids: [27, 53],
        movie_id: 1164355,
        original_language: "id",
        original_title: "Lembayung",
        overview: "Arum and Pica, who wanted to complete their internship at Lembayung hospital, had to face mysterious terror from a woman satan who was suspected of hanged herself in the bathroom. The situation became even more tense after they asked others for help to the point where they threatened their own lives and those closest to them.",
        popularity: 189.706,
        poster_path: "/5x9LrW0yvtt6S3XovIQHgXfYvLL.jpg",
        release_date: "2024-09-19",
        title: "Lembayung",
        video: false,
        vote_average: 7.8,
        vote_count: 6
    },
    {
        adult: false,
        backdrop_path: "/tL8fzn7JaBzRJKsE1W6GrVxmMQj.jpg",
        genre_ids: [80, 28, 53],
        movie_id: 866398,
        original_language: "en",
        original_title: "The Beekeeper",
        overview: "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
        popularity: 188.995,
        poster_path: "/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
        release_date: "2024-01-08",
        title: "The Beekeeper",
        video: false,
        vote_average: 7.34,
        vote_count: 3290
    },
    {
    adult: false,
    backdrop_path: "/iHYh4cdO8ylA3W0dUxTDVdyJ5G9.jpg",
    genre_ids: [878, 12, 28],
    movie_id: 653346,
    original_language: "en",
    original_title: "Kingdom of the Planet of the Apes",
    overview: "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
    popularity: 188.409,
    poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
    release_date: "2024-05-08",
    title: "Kingdom of the Planet of the Apes",
    video: false,
    vote_average: 7.1,
    vote_count: 3479
  },
  {
    adult: false,
    backdrop_path: "/5JrZAtyk3LwiiAWLW0kwz41XZJC.jpg",
    genre_ids: [12, 14, 28],
    movie_id: 122,
    original_language: "en",
    original_title: "The Lord of the Rings: The Return of the King",
    overview: "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
    popularity: 188.279,
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-17",
    title: "The Lord of the Rings: The Return of the King",
    video: false,
    vote_average: 8.483,
    vote_count: 24531
  },
  {
    adult: false,
    backdrop_path: "/P82NAcEsLIYgQtrtn36tYsj41m.jpg",
    genre_ids: [16, 35, 10751, 12, 28],
    movie_id: 748783,
    original_language: "en",
    original_title: "The Garfield Movie",
    overview: "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
    popularity: 186.651,
    poster_path: "/xYduFGuch9OwbCOEUiamml18ZoB.jpg",
    release_date: "2024-04-30",
    title: "The Garfield Movie",
    video: false,
    vote_average: 7.1,
    vote_count: 1175
  },
  {
    adult: false,
    backdrop_path: "/721p2lNSGp2iSlUUukZwCzEKrnn.jpg",
    genre_ids: [53, 99, 878],
    movie_id: 1023915,
    original_language: "en",
    original_title: "2073",
    overview: "Inspired by Chris Marker's iconic 1962 featurette La Jetée; the year is 2073—a not-so-distant dystopian future—and the setting is New San Francisco, the scorched-earth tech-dominant police state where democracy and personal freedom have been well and truly obliterated.",
    popularity: 186.62,
    poster_path: "/l67ir3kU53FYd6Vjwhqrkih1H1P.jpg",
    release_date: "2024-12-27",
    title: "2073",
    video: false,
    vote_average: 7.016,
    vote_count: 32
  },
  {
    adult: false,
    backdrop_path: "/4r7e8KNcjmb8eAt3MzKZpcuIjAn.jpg",
    genre_ids: [28, 878, 53, 35, 27],
    movie_id: 995803,
    original_language: "en",
    original_title: "Arena Wars",
    overview: "In 2045 convicted criminals are given the opportunity to compete on the world's #1 televised sporting event, Arena Wars. They must survive 7 rooms and 7 of the most vicious killers in the country. If they win, they regain their freedom.",
    popularity: 186.203,
    poster_path: "/4dRtXjk1rcsZlaMJpBn6Nh9cTfO.jpg",
    release_date: "2024-06-25",
    title: "Arena Wars",
    video: false,
    vote_average: 5.2,
    vote_count: 41
  },
  {
    adult: false,
    backdrop_path: "/wsE1ScIiFdKl9RLuaI8pTn4rjxR.jpg",
    genre_ids: [10770, 80, 18, 14, 53, 16],
    movie_id: 51482,
    original_language: "ja",
    original_title: "DEATH NOTE リライト ～幻視する神～",
    overview: "A recap of Death Note episodes 1–26, with new footage. When rogue shinigami Ryuk leaves his Death Note in the human world, he has no idea how far the one who finds it will take his new-found power. With the Death Note in hand, brilliant high school student Light Yagami vows to rid the world of evil.",
    popularity: 186.126,
    poster_path: "/qDhbGqjZ7yFwa7FMIzuiQTQMfEQ.jpg",
    release_date: "2007-08-31",
    title: "Death Note Relight 1: Visions of a God",
    video: false,
    vote_average: 8.1,
    vote_count: 315
  },
  {
    adult: false,
    backdrop_path: "/wcUohmHc9oDZXarXDp905TYVui4.jpg",
    genre_ids: [18, 10749],
    movie_id: 82023,
    original_language: "de",
    original_title: "Hotel Desire",
    overview: "Antonia is a single mother who works as a hotel maid in Berlin. A normal hot summer day takes a dramatic turn when she crosses paths with a particular guest of the hotel, famous blind portrait painter Julius Pass.",
    popularity: 185.234,
    poster_path: "/myzQj8Rk178DrWsiZjVKjz7Kj9P.jpg",
    release_date: "2011-12-07",
    title: "Hotel Desire",
    video: false,
    vote_average: 6,
    vote_count: 115
  },
  {
    adult: false,
    backdrop_path: "/kwXycPsLA6SV3KUOagn343TtMOf.jpg",
    genre_ids: [28, 878, 53],
    movie_id: 791042,
    original_language: "en",
    original_title: "Levels",
    overview: "After witnessing his girlfriend's murder, a man risks everything - including reality itself - to discover the truth.",
    popularity: 184.789,
    poster_path: "/y1xm0jMIlx9Oo2a3jWNyLGm43sJ.jpg",
    release_date: "2024-11-01",
    title: "Levels",
    video: false,
    vote_average: 5.5,
    vote_count: 49
  },
  {
    adult: false,
    backdrop_path: "/f0p60RMGFug62NkmLdKNIHuoWVJ.jpg",
    genre_ids: [878, 12, 35, 10751],
    movie_id: 1401586,
    original_language: "en",
    original_title: "Sonic the Hedgehog 4",
    overview: "The fourth installment in the Sonic the Hedgehog film franchise. Plot details and crew are unconfirmed.",
    popularity: 184.175,
    poster_path: "/t8uoHBODkFlSQJRL6qc4IclUBlH.jpg",
    release_date: "2027-03-19",
    title: "Sonic the Hedgehog 4",
    video: false,
    vote_average: 0,
    vote_count: 0
  },
  {
    adult: false,
    backdrop_path: "/jbthbh0KzaUWFPYvkfmXAamjI8j.jpg",
    genre_ids: [16, 28, 12, 878],
    movie_id: 569094,
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview: "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    popularity: 179.753,
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    release_date: "2023-05-31",
    title: "Spider-Man: Across the Spider-Verse",
    video: false,
    vote_average: 8.353,
    vote_count: 7215
  },
  {
    adult: false,
    backdrop_path: "/9f2RQqntqWXmMkAzlsUx41f0utR.jpg",
    genre_ids: [16, 35],
    movie_id: 922806,
    original_language: "ja",
    original_title: "空色ユーティリティ",
    overview: "Three high schoolers, Minami, Ayaka, and Haruka, head out for a sunny day of relaxation at the golf course. Beginner Minami slowly gains confidence on the grass as she learns and laughs with the help and encouragement of her more experienced senpai.",
    popularity: 178.589,
    poster_path: "/c67w0Fge21YHnLqmdN6tjFCWpHQ.jpg",
    release_date: "2021-12-31",
    title: "Sorairo Utility",
    video: false,
    vote_average: 4.7,
    vote_count: 3
  },
  {
    adult: false,
    backdrop_path: "/awNgj3l5f1X6A0oCBnFl99X2K9R.jpg",
    genre_ids: [80, 53, 37],
    movie_id: 395817,
    original_language: "en",
    original_title: "The Thicket",
    overview: "An innocent young man, Jack, goes on an epic quest to rescue his sister Lula after she has been kidnapped by the violent killer Cut Throat Bill and her gang. To save her, Jack enlists the help of a crafty bounty hunter named Reginald Jones, a grave-digging alcoholic son of an ex-slave, and a street-smart prostitute. The gang tracks Cut Throat Bill into the deadly no-man’s land known as The Big Thicket — a place where blood and chaos reign.",
    popularity: 177.477,
    poster_path: "/ukqWWQrJRgJym6dsTt1x3EwR2Kp.jpg",
    release_date: "2024-09-05",
    title: "The Thicket",
    video: false,
    vote_average: 6.343,
    vote_count: 51
  },
  {
    adult: false,
    backdrop_path: "/z51Wzj94hvAIsWfknifKTqKJRwp.jpg",
    genre_ids: [12, 14, 28],
    movie_id: 120,
    original_language: "en",
    original_title: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
    popularity: 177.206,
    poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    release_date: "2001-12-18",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    video: false,
    vote_average: 8.418,
    vote_count: 25489
  },
  {
  adult: false,
  backdrop_path: "/xPVhaMMUZq1yclf4kCEYwJ1Cqr6.jpg",
  genre_ids: [27, 53],
  movie_id: 1100856,
  original_language: "ru",
  original_title: "Заклятье. Шепот ведьм",
  overview: "Mara, an ancient pagan spirit, hunts a group of teenagers taking their body parts to be reborn. A disillusioned and desperate investigator has to face his deepest fears to save the teenagers.",
  popularity: 176.649,
  poster_path: "/raDMchyq3dJMqso2TVh75A123Xb.jpg",
  release_date: "2024-06-13",
  title: "Whisper of the Witch",
  video: false,
  vote_average: 6.4,
  vote_count: 25
},
{
  adult: false,
  backdrop_path: "/sCzcYW9h55WcesOqA12cgEr9Exw.jpg",
  genre_ids: [18, 10749],
  movie_id: 597,
  original_language: "en",
  original_title: "Titanic",
  overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
  popularity: 175.786,
  poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
  release_date: "1997-11-18",
  title: "Titanic",
  video: false,
  vote_average: 7.9,
  vote_count: 25588
},
{
  adult: false,
  backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
  genre_ids: [18, 80],
  movie_id: 278,
  original_language: "en",
  original_title: "The Shawshank Redemption",
  overview: "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
  popularity: 175.407,
  poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
  release_date: "1994-09-23",
  title: "The Shawshank Redemption",
  video: false,
  vote_average: 8.709,
  vote_count: 27572
},
{
  adult: false,
  backdrop_path: "/3m0j3hCS8kMAaP9El6Vy5Lqnyft.jpg",
  genre_ids: [878, 27, 53],
  movie_id: 1125510,
  original_language: "es",
  original_title: "El hoyo 2",
  overview: "After a mysterious leader imposes his law in a brutal system of vertical cells, a new arrival battles against a dubious food distribution method.",
  popularity: 174.149,
  poster_path: "/tvIpBg12IIA5Dr9Sjn38ygS1vQp.jpg",
  release_date: "2024-09-27",
  title: "The Platform 2",
  video: false,
  vote_average: 5.6,
  vote_count: 1047
},
{
  adult: false,
  backdrop_path: "/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",
  genre_ids: [53, 28, 80, 18],
  movie_id: 1126166,
  original_language: "en",
  original_title: "Flight Risk",
  overview: "A U.S. Marshal escorts a government witness to trial after he is accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman that had been sent to assassinate the informant. After they subdue him, they’re forced to fly together after discovering that there are others attempting to eliminate them.",
  popularity: 171.204,
  poster_path: "/4cR3hImKd78dSs652PAkSAyJ5Cx.jpg",
  release_date: "2025-01-22",
  title: "Flight Risk",
  video: false,
  vote_average: 6,
  vote_count: 10
},
{
  adult: false,
  backdrop_path: "/hmZnqijPaaACjenDkrbWcCmcADI.jpg",
  genre_ids: [18],
  movie_id: 549509,
  original_language: "en",
  original_title: "The Brutalist",
  overview: "Escaping post-war Europe, visionary architect László Tóth arrives in America to rebuild his life, his work, and his marriage to his wife Erzsébet after being forced apart during wartime by shifting borders and regimes. On his own in a strange new country, László settles in Pennsylvania, where the wealthy and prominent industrialist Harrison Lee Van Buren recognizes his talent for building. But power and legacy come at a heavy cost.",
  popularity: 170.958,
  poster_path: "/vP7Yd6couiAaw9jgMd5cjMRj3hQ.jpg",
  release_date: "2024-12-20",
  title: "The Brutalist",
  video: false,
  vote_average: 5.6,
  vote_count: 53
},
{
  adult: false,
  backdrop_path: "/n4ycOGj2tRLfINTJQ3wl0vNYqpR.jpg",
  genre_ids: [16, 14, 10751, 12, 35],
  movie_id: 592983,
  original_language: "en",
  original_title: "Spellbound",
  overview: "When a powerful spell turns her parents into giant monsters, a teenage princess must journey into the wild to reverse the curse before it's too late.",
  popularity: 170.841,
  poster_path: "/4dSrwXJNKtMtlkwJPgZMkjjuHvD.jpg",
  release_date: "2024-11-22",
  title: "Spellbound",
  video: false,
  vote_average: 6.8,
  vote_count: 203
},
{
  adult: false,
  backdrop_path: "/7Iz55ystlGDNlavsKnP7iaJeLma.jpg",
  genre_ids: [18, 10749, 53],
  movie_id: 216015,
  original_language: "en",
  original_title: "Fifty Shades of Grey",
  overview: "When college senior Anastasia Steele steps in for her sick roommate to interview prominent businessman Christian Grey for their campus paper, little does she realize the path her life will take. Christian, as enigmatic as he is rich and powerful, finds himself strangely drawn to Ana, and she to him. Though sexually inexperienced, Ana plunges headlong into an affair -- and learns that Christian's true sexual proclivities push the boundaries of pain and pleasure.",
  popularity: 168.273,
  poster_path: "/63kGofUkt1Mx0SIL4XI4Z5AoSgt.jpg",
  release_date: "2015-02-11",
  title: "Fifty Shades of Grey",
  video: false,
  vote_average: 5.882,
  vote_count: 11838
},
{
  adult: false,
  backdrop_path: "/vHJlbhsXrZ5yrO2KqCbGSIU6fRX.jpg",
  genre_ids: [28, 9648, 878, 53],
  movie_id: 198663,
  original_language: "en",
  original_title: "The Maze Runner",
  overview: "Set in a post-apocalyptic world, young Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.",
  popularity: 166.075,
  poster_path: "/ode14q7WtDugFDp78fo9lCsmay9.jpg",
  release_date: "2014-09-10",
  title: "The Maze Runner",
  video: false,
  vote_average: 7.188,
  vote_count: 17124
},
{
  adult: false,
  backdrop_path: "/s3FDBLH4qc1IcjexB05Qvbn3wxO.jpg",
  genre_ids: [28, 80, 53],
  movie_id: 449443,
  original_language: "en",
  original_title: "Den of Thieves",
  overview: "A gritty crime saga which follows the lives of an elite unit of the LA County Sheriff's Dept. and the state's most successful bank robbery crew as the outlaws plan a seemingly impossible heist on the Federal Reserve Bank.",
  popularity: 164.883,
  poster_path: "/dAP5NpkrMMczir5dUPjRR6ywqgz.jpg",
  release_date: "2018-01-18",
  title: "Den of Thieves",
  video: false,
  vote_average: 6.8,
  vote_count: 2916
},
{
    backdrop_path: "/czoiFndZswfFcQxbHxWUGcSpajM.jpg",
    movie_id: 1114894,
    title: "Star Trek: Section 31",
    original_title: "Star Trek: Section 31",
    overview: "Emperor Philippa Georgiou joins a secret division of Starfleet tasked with protecting the United Federation of Planets and faces the sins of her past.",
    poster_path: "/sqiCinCzUGlzQiFytS30N1nO3Pt.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [878, 12],
    popularity: 55.072,
    release_date: "2025-01-15",
    video: false,
    vote_average: 5.5,
    vote_count: 24
  },
  {
    backdrop_path: "/uwACVNL5OpiI3oT72DVGxnU4SRV.jpg",
    movie_id: 1232827,
    title: "The Girl with the Needle",
    original_title: "Pigen med nålen",
    overview: "Struggling to survive in post-WWI Copenhagen, a newly unemployed and pregnant young woman is taken in by a charismatic elder to help run an underground adoption agency. The two form an unexpected bond, until a sudden discovery changes everything.",
    poster_path: "/2xkyx8v9G3ePxe1IcFugFQkXHzQ.jpg",
    adult: false,
    original_language: "da",
    genre_ids: [18, 36, 53],
    popularity: 26.074,
    release_date: "2024-09-06",
    video: false,
    vote_average: 7.6,
    vote_count: 16
  },
  {
    backdrop_path: "/lrP1TQf3stZveNEyviUUcSh8HLA.jpg",
    movie_id: 675353,
    title: "Sonic the Hedgehog 2",
    original_title: "Sonic the Hedgehog 2",
    overview: "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
    poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [28, 12, 10751, 35],
    popularity: 359.906,
    release_date: "2022-03-30",
    video: false,
    vote_average: 7.488,
    vote_count: 5220
  },
  {
    backdrop_path: "/9mJ9dxCGpudxyBtlC0M9Y4pTyXN.jpg",
    movie_id: 1184918,
    title: "The Wild Robot",
    original_title: "The Wild Robot",
    overview: "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
    poster_path: "/9w0Vh9eizfBXrcomiaFWTIPdboo.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [16, 28, 878, 10751],
    popularity: 627.856,
    release_date: "2024-09-12",
    video: false,
    vote_average: 8.365,
    vote_count: 4079
  },
  {
    backdrop_path: "/c0g0OprcXkRu61HlKM1fQv8qj8x.jpg",
    movie_id: 1410082,
    title: "Sniper: The Last Stand",
    original_title: "Sniper: The Last Stand",
    overview: "To stop an arms dealer from unleashing a deadly superweapon, Ace sniper Brandon Beckett and Agent Zero are deployed to Costa Verde to lead a group of elite soldiers against an unrelenting militia. Taking an untested sniper under his wing, Beckett faces his newest challenge: giving orders instead of receiving them. With both time and ammo running low in a race to save humanity, the team must overcome all odds just to survive.",
    poster_path: "/TVvIyCsFCmLk9MRLbAZi4X8f32.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [28, 53],
    popularity: 135.912,
    release_date: "2025-01-21",
    video: false,
    vote_average: 6.2,
    vote_count: 5
  },
  {
    backdrop_path: "/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",
    movie_id: 1126166,
    title: "Flight Risk",
    original_title: "Flight Risk",
    overview: "A U.S. Marshal escorts a government witness to trial after he is accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman that had been sent to assassinate the informant. After they subdue him, they’re forced to fly together after discovering that there are others attempting to eliminate them.",
    poster_path: "/4cR3hImKd78dSs652PAkSAyJ5Cx.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [53, 28, 80, 18],
    popularity: 198.425,
    release_date: "2025-01-22",
    video: false,
    vote_average: 6.1,
    vote_count: 12
  },
  {
    backdrop_path: "/4WHRiFgbsAuSJ79fyr8pTXkj4G2.jpg",
    movie_id: 661539,
    title: "A Complete Unknown",
    original_title: "A Complete Unknown",
    overview: "New York, early 1960s. Against the backdrop of a vibrant music scene and tumultuous cultural upheaval, an enigmatic 19-year-old from Minnesota arrives in the West Village with his guitar and revolutionary talent, destined to change the course of American music.",
    poster_path: "/5tQYnwYrvr7XhYY7JZYLo7MYIVN.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [18, 10402, 36],
    popularity: 166.038,
    release_date: "2024-12-18",
    video: false,
    vote_average: 7.5,
    vote_count: 81
  },
  {
    backdrop_path: "/rRBD8ORo9y34tYkAQJVbn4Ml6tu.jpg",
    movie_id: 693134,
    title: "Dune: Part Two",
    original_title: "Dune: Part Two",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.",
    poster_path: "/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [878, 12],
    popularity: 265.251,
    release_date: "2024-02-27",
    video: false,
    vote_average: 8.2,
    vote_count: 6093
  },
  {
    backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
    movie_id: 558449,
    title: "Gladiator II",
    original_title: "Gladiator II",
    overview: "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [28, 12, 18],
    popularity: 1205.599,
    release_date: "2024-11-05",
    video: false,
    vote_average: 6.761,
    vote_count: 2481
  },
  {
    backdrop_path: "/bv9tOAIACAdQioCs80dKytYV3G7.jpg",
    movie_id: 989662,
    title: "A Different Man",
    original_title: "A Different Man",
    overview: "Aspiring actor Edward undergoes a radical medical procedure to drastically transform his appearance. But his new dream face quickly turns into a nightmare, as he loses out on the role he was born to play and becomes obsessed with reclaiming what was lost.",
    poster_path: "/lZZKTEvo92u1J5pm7QoEA5yN3du.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [35, 18, 53],
    popularity: 101.689,
    release_date: "2024-08-24",
    video: false,
    vote_average: 7.2,
    vote_count: 145
  },
  {
    backdrop_path: "/dhz2z8KpD5qd787CkEwPLo6rWpf.jpg",
    movie_id: 1249289,
    title: "Alarum",
    original_title: "Alarum",
    overview: "Two married spies caught in the crosshairs of an international intelligence network will stop at nothing to obtain a critical asset. Joe and Lara are agents living off the grid whose quiet retreat at a winter resort is blown to shreds when members of the old guard suspect the two may have joined an elite team of rogue spies, known as Alarum.",
    poster_path: "/v313aUGmMNj6yNveaiQXysBmjVS.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [28, 80, 53],
    popularity: 885.076,
    release_date: "2025-01-16",
    video: false,
    vote_average: 6.1,
    vote_count: 41
  },
  {
    backdrop_path: "/wwARk7hRIfHfh2n2ubN6N7lvTne.jpg",
    movie_id: 710295,
    title: "Wolf Man",
    original_title: "Wolf Man",
    overview: "With his marriage fraying, Blake persuades his wife Charlotte to take a break from the city and visit his remote childhood home in rural Oregon. As they arrive at the farmhouse in the dead of night, they're attacked by an unseen animal and barricade themselves inside the home as the creature prowls the perimeter. But as the night stretches on, Blake begins to behave strangely, transforming into something unrecognizable.",
    poster_path: "/tUtuMtC6oaRXr4x2B5Xi6ABdMCv.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [27, 53],
    popularity: 271.438,
    release_date: "2025-01-15",
    video: false,
    vote_average: 6.6,
    vote_count: 84
  },
  {
    backdrop_path: "/hctfNoMpQGfn3VXdBYb9p0P5bT5.jpg",
    movie_id: 1097549,
    title: "Babygirl",
    original_title: "Babygirl",
    overview: "A high-powered CEO puts her career and family on the line when she begins a torrid affair with her much younger intern.",
    poster_path: "/A8HbTd0FemZyFCh5qvJFpHGiwF8.jpg",
    adult: false,
    original_language: "en",
    genre_ids: [18],
    popularity: 263.303,
    release_date: "2024-12-25",
    video: false,
    vote_average: 5.7,
    vote_count: 134
  },
  {
      backdrop_path: "/zGT6zikFjC5wRROXbPIipKahZn8.jpg",
      movie_id: 850439,
      title: "The Damned",
      original_title: "The Damned",
      overview: "A 19th-century widow is tasked with making an impossible choice when, during an especially cruel winter, a ship sinks off the coast of her impoverished Icelandic fishing village. Any attempt to rescue survivors risks further depleting the starving villagers’ supplies.",
      poster_path: "/fAXDQny8kEquc1BImiQHhYMGSsW.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [18, 27, 9648],
      popularity: 64.567,
      release_date: "2025-01-03",
      video: false,
      vote_average: 6.1,
      vote_count: 18
    },
    {
      backdrop_path: "/vZG7PrX9HmdgL5qfZRjhJsFYEIA.jpg",
      movie_id: 912649,
      title: "Venom: The Last Dance",
      original_title: "Venom: The Last Dance",
      overview: "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [28, 878, 12],
      popularity: 1217.213,
      release_date: "2024-10-22",
      video: false,
      vote_average: 6.8,
      vote_count: 2524
    },
    {
      backdrop_path: "/st9M4O4imOuQVU35RMeYuEQfkvD.jpg",
      movie_id: 1140535,
      title: "Presence",
      original_title: "Presence",
      overview: "A family becomes convinced they are not alone after moving into their new home in the suburbs.",
      poster_path: "/6gwjrSIeaAulBBCjw8GoqSL3Mst.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [18, 27],
      popularity: 67.427,
      release_date: "2025-01-17",
      video: false,
      vote_average: 7,
      vote_count: 8
    },
    {
      backdrop_path: "/eP4RZSHliWu6lPT5WQyHr5ZZKuC.jpg",
      movie_id: 945961,
      title: "Alien: Romulus",
      original_title: "Alien: Romulus",
      overview: "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
      poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878],
      popularity: 396.649,
      release_date: "2024-08-13",
      video: false,
      vote_average: 7.225,
      vote_count: 3114
    },
    {
      backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
      movie_id: 1138194,
      title: "Heretic",
      original_title: "Heretic",
      overview: "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
      poster_path: "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53],
      popularity: 536.228,
      release_date: "2024-10-31",
      video: false,
      vote_average: 7.2,
      vote_count: 940
    },
    {
      backdrop_path: "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
      movie_id: 762509,
      title: "Mufasa: The Lion King",
      original_title: "Mufasa: The Lion King",
      overview: "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      poster_path: "/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [12, 10751, 16],
      popularity: 1755.179,
      release_date: "2024-12-18",
      video: false,
      vote_average: 7.438,
      vote_count: 844
    },
    {
      backdrop_path: "/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg",
      movie_id: 1241982,
      title: "Moana 2",
      original_title: "Moana 2",
      overview: "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      poster_path: "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [16, 12, 10751, 35, 9648],
      popularity: 1403.308,
      release_date: "2024-11-21",
      video: false,
      vote_average: 7.002,
      vote_count: 893
    },
    {
      backdrop_path: "/h3fwlwHotd3JfV13HdW0mxDcxPD.jpg",
      movie_id: 957119,
      title: "Sidelined: The QB and Me",
      original_title: "Sidelined: The QB and Me",
      overview: "Dallas, a burdened but headstrong dancer, is determined to get into the best dance school in the country—her late mother’s alma mater. However, that dream is suddenly derailed when the cheeky yet secretly grieving football star, Drayton, crashes into her life with a unique story of his own. Will the two of them be able to grow into their dreams together, or will their dreams be sidelined?",
      poster_path: "/1oV2rq7PEuKILrBd9vBL9bChRYf.jpg",
      adult: false,
      original_language: "en",
      genre_ids: [35, 10749],
      popularity: 519.926,
      release_date: "2024-11-29",
      video: false,
      vote_average: 6.6,
      vote_count: 120
    }
])

User.create([
  { name: "Alice", last_name: "Smith", email: "alice@example.com", password: "password123" },
  { name: "Bob", last_name: "Johnson", email: "bob@example.com", password: "secure456" }
])
